version: 1
disable_existing_loggers: true

formatters:
    standard:
        format: "[%(asctime)s] [%(process)d] [%(levelname)s]: %(message)s"
        datefmt: "%Y-%m-%dT%H:%M:%S%z"
    error:
        format: "[%(asctime)s] [%(process)d] [%(levelname)s]: %(message)s"
        datefmt: "%Y-%m-%dT%H:%M:%S%z"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: /tmp/info.log
        maxBytes: 10485760  # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        filename: /tmp/errors.log
        maxBytes: 10485760  # 10MB
        backupCount: 20
        encoding: utf8

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: /tmp/debug.log
        maxBytes: 10485760  # 10MB
        backupCount: 20
        encoding: utf8

    critical_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: CRITICAL
        formatter: standard
        filename: /tmp/critical.log
        maxBytes: 10485760  # 10MB
        backupCount: 20
        encoding: utf8

    warn_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARN
        formatter: standard
        filename: /tmp/warn.log
        maxBytes: 10485760  # 10MB
        backupCount: 20
        encoding: utf8

root:
    level: DEBUG
    handlers: [console]
    propagate: yes

loggers:
    default:
        level: INFO
        handlers: [console]
        propagate: no
    bandit:
        level: DEBUG
        handlers: [console]
        propagate: no
    apscheduler:
        level: WARN
        handlers: [ console ]
        propagate: yes
    fastapi:
        level: DEBUG
        handlers: [console]
        propagate: yes
    uvicorn:
        level: DEBUG
        handlers: [console]
        propagate: no