apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "master.fullname" . }}
  labels:
    prometheus: "true"
spec:
  selector:
    matchLabels:
      {{- include "master.selectorLabels" . | nindent 8 }}
  podMetricsEndpoints:
  - port: http
